### PR TITLE
Added Status Bar Item

### PR DESCRIPTION
**Pull request by Drumber**
Added status bar item that shows the time of the last successful sync. It can also be toggled off in the settings.

On hover it will show the exact date and time of the last sync.
screenshot
> The date is formatted using the default locale (here in German).

Small note:
I had to enable polyfills for http and https in the webpack config, as the build failed because of the @azure/msal-node dependency.

### CODE REVIEW

**Comment by fyears** [comment]
Thanks for your PR!

But, if you enable `http` polyfill, are the built artifacts still working on mobile?

**Comment by Drumber** [comment]
Hi, I've tested it on the latest Obsdian Android version and haven't encountered any problems so far.

**Comment by KosmosisDire** [comment]
@fyears Will this be merged anytime soon? It looks like an addition I would enjoy being able to use!

**Comment by fyears** [comment]
finally merged! thanks! i will see what adjustments i could do though

**Pull request merged**
