### PR TITLE
Fix typo in docs

### PR DESCRIPTION
**Pull request by davidangel**

### CODE REVIEW

**Comment by Aldekein** [comment]
I wanted to create a PR for this, but decided to check if it was noticed earlier.

**Comment by frozar** [comment]
Ah, same for me.
But the maintainer of this plugin seems to be in a long holiday ^^'

**Comment by sahil-sagwekar2652** [comment]
I always search if there is an existing issue or PR. But this one is pending for quite some time now. Hope the owner sees it soon.

**Comment by fyears** [comment]
thx!

**Pull request merged**
